# Generated by Django 5.0.1 on 2024-02-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=20, verbose_name='email')),
                ('password', models.CharField(max_length=20)),
                ('avatars', models.FileField(max_length=20, null=True, upload_to='')),
                ('date', models.CharField(max_length=10)),
                ('introduction', models.CharField(max_length=50, null=True)),
                ('phonenumber', models.CharField(max_length=15, null=True)),
                ('nickname', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
