# Generated by Django 5.0.1 on 2024-03-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_status_alter_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatars',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='用户头像'),
        ),
    ]
