# Generated by Django 5.0.1 on 2024-03-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_avatars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(max_length=288, null=True),
        ),
    ]
