# Generated by Django 5.0.1 on 2024-04-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_user_introduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('orderid', models.CharField(max_length=40, unique=True)),
                ('textdetail', models.TextField()),
                ('filedetail', models.JSONField(null=True)),
                ('createdate', models.CharField(max_length=20, verbose_name='创建时间的时间戳')),
                ('titel', models.CharField(max_length=100)),
                ('money', models.FloatField(default=0.0)),
                ('deadline', models.CharField(max_length=50, verbose_name='期限')),
                ('type', models.CharField(max_length=50)),
                ('payment', models.CharField(max_length=5, null=True, verbose_name='付款情况')),
                ('takename', models.CharField(max_length=50, null=True, verbose_name='接单者')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(null=True),
        ),
    ]
