# Generated by Django 5.0.1 on 2024-04-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_t_fdetail_rename_titel_projectdetail_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='orderid',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
