# Generated by Django 5.0.1 on 2024-04-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_projectdetail_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_fdetail',
            name='uuidname',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
