# Generated by Django 5.0.1 on 2024-04-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_t_fdetail_uuidname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_fdetail',
            name='path',
            field=models.FilePathField(null=True, path=None),
        ),
    ]
