# Generated by Django 5.0.1 on 2024-04-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_t_fdetail_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='finish',
            field=models.CharField(default=None, max_length=20, verbose_name='完成情况'),
        ),
    ]
