# Generated by Django 5.0.1 on 2024-05-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_projectdetail_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='deadline',
            field=models.DateTimeField(max_length=50, verbose_name='期限'),
        ),
    ]
