# Generated by Django 5.0.1 on 2024-05-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_projectdetail_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='deadline',
            field=models.IntegerField(null=True, verbose_name='期限'),
        ),
    ]
