# Generated by Django 5.0.1 on 2024-05-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_projectdetail_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='createdate',
            field=models.IntegerField(verbose_name='创建时间的时间戳'),
        ),
    ]
