# Generated by Django 5.0.1 on 2024-05-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_projectdetail_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='finish',
            field=models.CharField(max_length=20, null=True, verbose_name='完成情况'),
        ),
    ]
