# Generated by Django 5.0.1 on 2024-05-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_projectdetail_finish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_user', models.CharField(max_length=50)),
                ('to_user', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('content', models.TextField(null=True)),
                ('senddate', models.IntegerField(verbose_name='创建时间的时间戳')),
                ('uuidname', models.CharField(max_length=50, null=True)),
                ('lookover', models.BooleanField(default=False)),
            ],
        ),
    ]
