# Generated by Django 5.0.1 on 2024-05-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userid',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
