# Generated by Django 5.0.1 on 2024-05-27 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_user_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
