# Generated by Django 5.0.1 on 2024-05-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('from_user', models.CharField(max_length=50)),
                ('to_user', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('content', models.TextField(null=True)),
                ('senddate', models.IntegerField(verbose_name='创建时间的时间戳')),
                ('uuidname', models.CharField(max_length=50, null=True, verbose_name='file_uuidname')),
                ('unread', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('uuid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('path', models.FilePathField(path=None)),
            ],
        ),
    ]
