# Generated by Django 5.0.1 on 2024-05-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_message_messagefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagefile',
            name='adddate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='unread',
            field=models.BooleanField(null=True),
        ),
    ]
