# Generated by Django 5.0.1 on 2024-06-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_messagefile_adddate_alter_message_unread'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishOrder',
            fields=[
                ('orderid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('t_fcontent', models.JSONField(null=True, verbose_name='包含了文本和文件的具体位置和内容')),
            ],
        ),
        migrations.AlterField(
            model_name='t_fdetail',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
