# Generated by Django 5.0.1 on 2024-06-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_finishorder_finish_alter_projectdetail_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='finish',
            field=models.BooleanField(null=True, verbose_name='完成情况'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='payment',
            field=models.BooleanField(null=True, verbose_name='付款情况'),
        ),
    ]
